game:
  grid_size: 20
  initial_speed: 5
  speed_increment: 0.5
  max_speed: 15
  initial_length: 3
  
graphics:
  window_width: 800
  window_height: 600
  fullscreen: false
  vsync: true
  msaa: 4
  
controls:
  forward: "w"
  backward: "s"
  left: "a"
  right: "d"
  up: "j"
  down: "k"
  pause: "h"
  quit: "l"
  
colors:
  snake_head: [0, 1, 0]
  snake_body: [0, 0.8, 0]
  food: [1, 0, 0]
  grid: [0.5, 0.5, 0.5]
  background: [0.1, 0.1, 0.2]
