game:
  grid_size: 20
  initial_speed: 3
  speed_increment: 0.3
  max_speed: 12
  initial_length: 3
  
graphics:
  window_width: 800
  window_height: 600
  fullscreen: false
  vsync: true
  
controls:
  forward: "arrowup"
  backward: "arrowdown"
  left: "arrowleft"
  right: "arrowright"
  pause: "p"
  quit: "escape"
  
colors:
  snake_head: [0.8, 0.3, 1.0]  # Purple
  snake_body: [1.0, 0.5, 0.0]  # Orange
  food: [1.0, 0.2, 0.0]        # Red-orange
  grid: [0.2, 0.8, 0.2]        # Eerie green
  background: [0.1, 0.0, 0.2]  # Dark purple
